// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHosts() {
  return window['go']['userData']['Hosts']['GetHosts']();
}

export function SaveSetting(arg1) {
  return window['go']['userData']['Hosts']['SaveSetting'](arg1);
}
