// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {userData} from '../models';

export function GetHosts():Promise<Array<userData.HostConfig>>;

export function RemoveHost(arg1:number):Promise<void>;

export function SaveSetting(arg1:userData.HostConfig):Promise<void>;
