// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetHosts():Promise<Array<service.HostConfig>>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RemoveHost(arg1:number):Promise<void>;

export function SaveSetting(arg1:service.HostConfig):Promise<void>;
