// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHosts() {
  return window['go']['service']['Hosts']['GetHosts']();
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['service']['Hosts']['OpenFileDialog'](arg1, arg2, arg3);
}

export function RemoveHost(arg1) {
  return window['go']['service']['Hosts']['RemoveHost'](arg1);
}

export function SaveSetting(arg1) {
  return window['go']['service']['Hosts']['SaveSetting'](arg1);
}
