// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerStatus():Promise<{[key: string]: boolean}>;

export function ShutdownServer():Promise<void>;

export function StartServer():Promise<boolean>;
