// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerStatus() {
  return window['go']['service']['Service']['GetServerStatus']();
}

export function ShutdownServer() {
  return window['go']['service']['Service']['ShutdownServer']();
}

export function StartServer() {
  return window['go']['service']['Service']['StartServer']();
}
