// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['service']['Setting']['GetSettings']();
}

export function OpenConfigFolder() {
  return window['go']['service']['Setting']['OpenConfigFolder']();
}

export function SaveSettings(arg1) {
  return window['go']['service']['Setting']['SaveSettings'](arg1);
}
