// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetSettings():Promise<service.Setting>;

export function OpenConfigFolder():Promise<void>;

export function SaveSettings(arg1:service.Setting):Promise<boolean>;
